# Generated by Django 4.2.4 on 2023-08-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
